version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # Agent communication
    volumes:
      #- ./jenkins_home:/var/jenkins_home
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /usr/bin/docker:/usr/bin/docker
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # allow Jenkins to use host Docker
    restart: unless-stopped

  calculator:
    build: .
    container_name: calculator
    ports:
      - "80:5000"   # expose calculator on host port 80
    restart: unless-stopped

volumes:
  jenkins_home: